name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest] 
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features experimental-api --all --all-targets
    - name: Run tests
      run: cargo test --features test,experimental-api --all-targets
